services:
  - type: web
    name: papermerge-core
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn papermerge.core.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PAPERMERGE__SECURITY__SECRET_KEY
        value: your_secret_key
      - key: PAPERMERGE__DATABASE__URL
        value: sqlite:///./papermerge.db
      - key: PAPERMERGE__MAIN__MEDIA_ROOT
        value: ./media
